### ISSUE TITLE
Windows-only test failure 

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#632]
fails every time now

```
[error] Test scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate failed: java.nio.file.InvalidPathException: Illegal char <:> at index 3: ./Y:\jenkins\workspace\scala-2.12.x-integrate-windows, took 1.439 sec
[error]     at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error]     at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error]     at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[error]     at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[error]     at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[error]     at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
[error]     at scala.tools.nsc.PipelineMainClass.cachePath(PipelineMain.scala:44)
[error]     at scala.tools.nsc.PipelineMainClass.$anonfun$process$20(PipelineMain.scala:172)
[error]     at scala.tools.nsc.PipelineMainClass.$anonfun$process$20$adapted(PipelineMain.scala:171)
[error]     at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
[error]     at scala.tools.nsc.PipelineMainClass.process(PipelineMain.scala:171)
[error]     at scala.tools.nsc.PipelineMainTest.$anonfun$check$1(PipelineMainTest.scala:64)
[error]     at scala.tools.nsc.PipelineMainTest.build$1(PipelineMainTest.scala:61)
[error]     at scala.tools.nsc.PipelineMainTest.$anonfun$check$3(PipelineMainTest.scala:72)
[error]     at scala.tools.nsc.PipelineMainTest.check(PipelineMainTest.scala:71)
[error]     at scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate(PipelineMainTest.scala:36)
[error]     ...
```

the first failure was  https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/1371/ which suggests the following list of possible culprits:

```
PipelineMain: add test, make it more testable and less buggy. (detail / githubweb)
Add experimental support for outline typing (detail / githubweb)
Deal with unpositioned Javac diagnostic messages (detail / githubweb)
[backport] Drop leaky encoding from JavaParser (detail / githubweb)
Test for backported fix in prior commit (pls merge forward) (detail / githubweb)
Fix chrome trace output for outline typing strategy (detail / githubweb)
Add comments to test (detail / githubweb)
```

cleanup in aisle @retronym?

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/8126.

**Comment by SethTisue** [comment]
@retronym this seems not fixed, error is different now, see e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/1390/

```
[error] Test scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate failed: java.nio.file.AccessDeniedException: y:\jenkins\tmp\pipelineBase3832251533991493145\projects\b1\p1\target, took 1.43 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
[error]     at java.nio.file.Files.createDirectory(Files.java:674)
[error]     at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
[error]     at java.nio.file.Files.createDirectories(Files.java:767)
[error]     at scala.tools.nsc.PipelineMainTest$CleanVisitor$1.preVisitDirectory(PipelineMainTest.scala:267)
[error]     at scala.tools.nsc.PipelineMainTest$CleanVisitor$1.preVisitDirectory(PipelineMainTest.scala:263)
[error]     at java.nio.file.Files.walkFileTree(Files.java:2677)
[error]     at java.nio.file.Files.walkFileTree(Files.java:2742)
[error]     at scala.tools.nsc.PipelineMainTest.clean(PipelineMainTest.scala:272)
[error]     at scala.tools.nsc.PipelineMainTest.check(PipelineMainTest.scala:70)
[error]     at scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate(PipelineMainTest.scala:36)
[error]     ...
[error] Test scala.tools.nsc.PipelineMainTest.pipelineMainBuildsCombined failed: java.nio.file.AccessDeniedException: y:\jenkins\tmp\pipelineBase950675618956427478\projects\b1\p1\target, took 0.887 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
[error]     at java.nio.file.Files.createDirectory(Files.java:674)
[error]     at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
[error]     at java.nio.file.Files.createDirectories(Files.java:767)
[error]     at scala.tools.nsc.PipelineMainTest$CleanVisitor$1.preVisitDirectory(PipelineMainTest.scala:267)
[error]     at scala.tools.nsc.PipelineMainTest$CleanVisitor$1.preVisitDirectory(PipelineMainTest.scala:263)
[error]     at java.nio.file.Files.walkFileTree(Files.java:2677)
[error]     at java.nio.file.Files.walkFileTree(Files.java:2742)
[error]     at scala.tools.nsc.PipelineMainTest.clean(PipelineMainTest.scala:272)
[error]     at scala.tools.nsc.PipelineMainTest.check(PipelineMainTest.scala:70)
[error]     at scala.tools.nsc.PipelineMainTest.pipelineMainBuildsCombined(PipelineMainTest.scala:40)
[error]     ...
```
